### ISSUE TITLE
Test support for xls/xlsx

### ISSUE THREAD

**Issue by sonalgoyal** [zinggAI/zingg#19]
Build a new febrl test file in XLS/XLSX format and test it

**Comment by navinrathore** [comment]
The "spark-excel" library can support excel files in spark
```
<!-- https://mvnrepository.com/artifact/com.crealytics/spark-excel -->
<dependency>
	<groupId>com.crealytics</groupId>
	<artifactId>spark-excel_${scala.binary.version}</artifactId>
	<version>3.1.2_0.16.4</version>
</dependency>
```
The *.xls files have been successfully tested for reading. however, *.xlsx file reading is not successful. It does not give any clear message
```
WARN  zingg.client.Client - Apologies for this message. Zingg has encountered an error. Factory
```
Tested with both v1, v2 APIs for this library. The .xlsx file has been created with MS excel. Spark 3.1.2 has been used.

**Comment by sonalgoyal** [comment]
@gnanaprakash-ravi can you try this? you can add the extra jars through zingg.conf (https://docs.zingg.ai/zingg/stepbystep/zingg-runtime-properties) and see if we can read and write xls. if so, please add the documentation on how to do so.

**Comment by Chandanydv1234** [comment]
### Excel (XLS/XLSX) support — how to configure

Documenting this here on the issue rather than in the main docs — Excel isn't a commonly used pipe for Zingg, so we're keeping it out of the primary documentation. It works today; here's the full setup.

Zingg reads and writes `.xls` / `.xlsx` via the [spark-excel](https://github.com/crealytics/spark-excel) connector. Spark has no native Excel support, so the connector jar has to be on the classpath at runtime. Both `.xls` and `.xlsx` use the same `com.crealytics.spark.excel` format string; the extension in `location` decides the workbook format on write.

#### 1. Add the spark-excel jar

Pick the artifact matching your Spark/Scala versions — coordinate is `com.crealytics:spark-excel_<scala>:<spark>_<connector>`. For Spark 3.5.x / Scala 2.12: `com.crealytics:spark-excel_2.12:3.5.1_0.20.4`. Add it either way in your [runtime properties](https://github.com/zinggAI/zingg) (`zingg.conf`):

```properties
# Option A — a downloaded jar (plus its transitive deps)
spark.jars=/path/to/spark-excel_2.12-3.5.1_0.20.4.jar

# Option B — let Spark resolve from Maven
spark.jars.packages=com.crealytics:spark-excel_2.12:3.5.1_0.20.4
```

#### 2. Read Excel as a source

```json
"data" : [{
    "name": "test",
    "format": "com.crealytics.spark.excel",
    "props": {
        "location": "examples/febrl/test.xlsx",
        "header": "true",
        "dataAddress": "'febrl'!A1"
    },
    "schema": "recId string, fname string, lname string, stNo string, add1 string, add2 string, city string, areacode string, state string, dob string, ssn string"
}]
```

#### 3. Write Excel as a sink

```json
"output" : [{
    "name": "output",
    "format": "com.crealytics.spark.excel",
    "props": {
        "location": "/tmp/zinggOutput.xlsx",
        "header": "true",
        "dataAddress": "'output'!A1"
    }
}]
```

#### Useful `props` (passed straight through to spark-excel)

| Option | Description |
| --- | --- |
| `header` | `true` if the first row holds column names. |
| `dataAddress` | Sheet/cell range to read or write, e.g. `'febrl'!A1`. Defaults to the first sheet. |
| `inferSchema` | Infer column types when no `schema` is supplied. Prefer an explicit `schema`. |
| `usePlainNumberFormat` | Read numeric cells without scientific/locale formatting. |

#### Full runnable example

A complete febrl config (`configExcel.json`) and the `test.xlsx` dataset are on the PR branch [`xls-xlsx-support`](https://github.com/zinggAI/zingg/pull/1347/files) (PR #1347). The field definition is the standard febrl setup — `recId` as `DONT_USE`, and `fname, lname, stNo, add1, add2, city, areacode, state, dob, ssn` as `FUZZY`.

Run it with any phase, e.g.:

```bash
./scripts/zingg.sh --phase match --conf examples/febrl/configExcel.json
```

#### Verified

- **Read/write round-trip:** wrote febrl data to `test.xlsx` and read it back — 65 rows both ways, schema and data intact (including a unicode row). The `.xlsx` read that originally failed here now works.
- **End-to-end:** ran the `match` phase with `configExcel.json` — Zingg read from `test.xlsx`, matched, and wrote clustered output to `.xlsx`; duplicates grouped correctly.
- **Environment:** Spark 3.5.1 (Scala 2.12), `spark-excel_2.12:3.5.1_0.20.4`.

Closing the docs PR (#1347) without merging, since we're not adding Excel to the main docs — this comment is the reference.
