### ISSUE TITLE
Obvious dupes python api 

### ISSUE THREAD

**Issue by sonalgoyal** [zinggAI/zingg#700]
verify it exists

**Comment by vikasgupta78** [comment]
Obvious dupes exists for python but it needs to be updated for recent changes in which instead of taking a string for obv dupe we have started taking it as ObviousDupes object.

So changes needed:

1. Create ObviousDupes class in python client.py referring to java ObviousDupes class
2. Update Arguments class in client.py to use the ObviousDupes
3. Update any impact due to above in any of the other python classes /methods
4. Update (if any) obv dupe python example using old obv dupe str

**Comment by sonalgoyal** [comment]
no longer relevant in oss, closing
