### ISSUE TITLE
better way to bump versions

### ISSUE THREAD

**Issue by sonalgoyal** [zinggAI/zingg#72]
right now we go to each pom and do the zingg deps and versions manually. it is a pain :-(

**Comment by navinrathore** [comment]
In the parent pom, a parameter for version can be defined and same can be referenced wherever needed.

However, here is the below warning message in mvn Reactor Build order analysis.
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for zingg:core:jar:0.3.1-SNAPSHOT
[WARNING] 'version' contains an expression but should be a constant. @ zingg:parent:${parent.version}, /home/work/product/final/zingg-1/pom.xml, line 6, column 11
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for zingg:parent:pom:0.3.1-SNAPSHOT
[WARNING] 'version' contains an expression but should be a constant. @ zingg:parent:${parent.version}, /home/work/product/final/zingg-1/pom.xml, line 6, column 11
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]
